---
kind: pipeline
type: docker
name: test

steps:
- name: test
  image: golang:1.19-alpine3.16
  commands:
  - apk add --no-cache build-base
  - go test -v ./...
  - go build
  when:
    event:
    - pull_request
- name: security
  image: golang:1.19-alpine3.16
  commands:
    - apk add --no-cache build-base
    - wget -O - -q https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.13.1
    - gosec ./...
trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: release

steps:
- name: test
  image: golang:1.19-alpine3.16
  commands:
    - apk add --no-cache build-base
    - go test -v ./...
- name: build
  image: golang:1.19-alpine3.16
  commands:
    - apk add --no-cache build-base bash
    - bash ./scripts/build-multiplatform.sh ${DRONE_TAG##v}
    - ls -l flowgre_*
- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_TOKEN
    files:
      - flowgre_*
    note: 'Flowgre, version ${DRONE_TAG}'
    title: '${DRONE_TAG}'
    prerelease: true
trigger:
  ref:
    - refs/tags/*
---
kind: signature
hmac: 805ea17fb5621c55f509b8bb8121037d61b2bfded3b996bd4703fd2738c3dae7

...
