---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.19-alpine3.16
  commands:
  - apk add --no-cache build-base
  - go test -v ./...
  - go build
  when:
    event:
    - pull_request
trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.19-alpine3.16
  commands:
    - apk add --no-cache build-base
    - go test -v ./...
- name: build
  image: golang:1.19-alipine3.16
  commands:
    - apk add --no-cache build-base
    - ./scripts/build-multiplatform.sh
- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_TOKEN
    files:
      - flowgre_*
    note: 'Flowgre, version ${DRONE_TAG}.'
    title: '${DRONE_TAG}'
    prerelease: true
trigger:
  ref:
    - refs/tags/*
---
kind: signature
hmac: 7dda79f39df64f958e0b5270164ac947e2e67897ca0e1d4017ddab648da9cc49

...
