---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.19-alpine3.16
  commands:
  - apk add --no-cache build-base
  - go test -v ./...
  - go build

trigger:
  event:
    - pull_request
---
kind: signature
hmac: d92166f06af8fd0efaac3d259dc282965ffce6068d9a49ed0cc004fae1ba260a

...
