---
kind: pipeline
type: docker
name: test

steps:
- name: test
  image: golang:1.19-alpine3.16
  commands:
  - apk add --no-cache build-base
  - go test -v ./...
  - go build
trigger:
  event:
    - pull_request
    - tag

---
kind: pipeline
type: docker
name: security

steps:
- name: gosec
  image: golang:1.19-alpine3.16
  commands:
    - wget -O - -q https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.13.1
    - ./bin/gosec ./...
- name: security_trivy
  image: golang:1.19-alpine3.16
  commands:
    - wget -O - -q https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s v0.32.1
    - ./bin/trivy fs .
trigger:
  event:
    - pull_request
    - tag

---
kind: pipeline
type: docker
name: release

steps:
- name: build
  image: golang:1.19-alpine3.16
  commands:
    - apk add --no-cache build-base bash
    - bash ./scripts/build-multiplatform.sh ${DRONE_TAG##v}
    - ls -l flowgre_*
- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_TOKEN
    files:
      - flowgre_*
    note: 'Flowgre, version ${DRONE_TAG}'
    title: '${DRONE_TAG}'
    prerelease: true
trigger:
  event:
    - tag

---
kind: signature
hmac: 515c17eab2781704824d9be1701fe7ae2b11bbd4a23b2f8d81c4a7fbc1b17f32

...
