---
kind: pipeline
type: docker
name: test

steps:
- name: test
  image: golang:1.19-alpine3.16
  commands:
  - apk add --no-cache build-base
  - go test -v ./...
  - go build
trigger:
  event:
    - pull_request
    - tag

---
kind: pipeline
type: docker
name: security

steps:
- name: gosec
  image: golang:1.19-alpine3.16
  commands:
    - wget -O - -q https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.13.1
    - ./bin/gosec ./...
- name: trivy
  image: golang:1.19-alpine3.16
  commands:
    - wget -O - -q https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s v0.32.1
    - ./bin/trivy fs .
trigger:
  event:
    - pull_request
    - tag

---
kind: pipeline
type: docker
name: release

steps:
- name: build
  image: golang:1.19
  commands:
    - bash ./scripts/build-multiplatform.sh ${DRONE_TAG##v}
    - ls -l flowgre_*
- name: build-musl
  image: golang:1.19-alpine3.16
  commands:
    - apk add --no-cache build-base
    - go build -ldflags '-s -w' -a -o flowgre_linux_amd64_musl_${DRONE_TAG##v}
    - ls -l flowgre_*
- name: generate_sbom
  image: golang:1.19-alpine3.16
  commands:
    - wget -O - -q https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s v0.32.1
    - ./bin/trivy fs --format cyclonedx --output sbom_${DRONE_TAG##v}.json .
- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_TOKEN
    files:
      - flowgre_*
      - sbom_*
    note: 'Flowgre, version ${DRONE_TAG}'
    title: '${DRONE_TAG}'
    prerelease: true
trigger:
  event:
    - tag

---
kind: signature
hmac: e6f7672bf89a8c993fa72fd992152689e61d921460837231fbb9c81b1e24c3a3

...
