name: Security

on:
  pull_request: {}
  push:
    tags:
      - 'v*'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install and run gosec
      run: |
        curl -sSfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.19.0
        ./bin/gosec ./...

    - name: Install and run trivy
      run: |
        curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s v0.51.1
        ./bin/trivy fs .